### ISSUE TITLE
Ide Blockers for Alpha Release

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow-meta#10]
We currently facing a few issues during registration:
- [x] **_Multiple Registrations in MetaPluginRegistrarComponent_**
```
metaPlugin.registerMetaComponents(project, configuration)
```
As of today we're applying for each Project window the `IdeMetaPlugin`, thus `Extensions`, which are applied on `Application` level will have duplicates. 

- [x] **_Undisposed Extensions_**
The `Disposable` in `ExtensionProvider` needs to be disposed, same applies for `MetaPluginRegistrarComponent#disposeComponent`. If not, all registered Extensions are not removed from memory, which leads to memory leaks and higher RAM consumptions. Possible solutions encompase to lift `MetaPluginRegistrarComponent` to an `ApplicationComponent` and define a `Disposable` strategy without the need of the `PicoContainer`, but this is an open discussion.

- [x] **_Make Extensions dumbAware_**
We'll need to indicate `Extensions`, which are available during `Indexing` and supply that in the `IdeSyntax`. `DumbAware` and `DumbService` should facilitate us with sufficient tools.

These need to be dealt with after we have a sufficient test environment and before we release the Alpha. The first 2 have High Priority, where as the last is a minor fix we can do after the release. Feel free to correct me @jansorg.
We are open for suggestions.

**Comment by jansorg** [comment]
@i-walker cc @raulraja  here are some notes how the issues above could be solved 

PR # is changing `idea-plugin` to simplify the necessary changes, which are outlined below.

# Multiple registrations
The main point is that there are application extensions and project extensions.

There's only one instance of [Application](https://github.com/JetBrains/intellij-community/blob/192/platform/core-api/src/com/intellij/openapi/application/Application.java) for an IntelliJ process. Application extensions are only registered once.

There's an arbitrary number of instances of a [Project](https://github.com/JetBrains/intellij-community/blob/192/platform/core-api/src/com/intellij/openapi/project/Project.java) for an IntelliJ process (0 for no open project, 2 for two open projects, etc.)
Project level extensions have to be registered once for each of the projects. They are unregistered and disposed when the project is closed. This happens, for example, when you close a project window.

Application extensions use [ExtensionPointName](https://github.com/JetBrains/intellij-community/blob/192/platform/extensions/src/com/intellij/openapi/extensions/ExtensionPointName.java)

Project extensions use [ProjectExtensionPointName](https://github.com/JetBrains/intellij-community/blob/192/platform/extensions/src/com/intellij/openapi/extensions/ProjectExtensionPointName.java)

Extensions inheriting from `LanguageExtension` seem to be registered as application extensions ([source](https://github.com/JetBrains/intellij-community/blob/192/platform/core-api/src/com/intellij/lang/LanguageExtensionPoint.java#L31).

## What we're currently doing
Currently all Arrow extensions are registered when a project is opened ([source](https://github.com/arrow-kt/arrow-meta/blob/master/idea-plugin/src/main/kotlin/arrow/meta/ide/MetaPluginRegistrarComponent.kt#L11)).

Types of currently supported extensions:
- Application extensions:
  - DiagnosticSuppressor
  - LineMarkerProvider
  - Actions
  - ColorSyntax
  - *more*, as far as I can tell all of the existing extensions idea-plugin is supporting.

- Project extensions
  - none I could find in the current sources of `idea-plugin`. But this will come up when more types of extensions are added. You can search for usages of `ProjectExtensionPointName` to see which extensions are of this type.

## What needs to be done
- [ ] register application extensions only once. Currently `IdeMetaPlugin().registerMetaComponents(project, configuration)` takes a project. For application extensions there's no instance of a `Project` available. Registration has to work without it. This could be named `IdeMetaPlugin().registerMetaApplicationComponents(app, configuration)`, for example.
- [ ] `IdeMetaPlugin().registerMetaComponents(project, configuration)` may be called to setup project extensions. Setup code which should only be called once during the lifetime of the application should probably be moved to the application setup code. For example, `installArrowPlugin()` is called there.
- [ ] the optimal case is to add a test to make sure that Meta's default IDE extensions are only setup once.

**Comment by raulraja** [comment]
All proposed changes looks good to me and thanks for explaining the different project vs application lifecycles

**Comment by i-walker** [comment]
We can close this issue as it was addressed in #62 and merged with #519
