### ISSUE TITLE
idea-plugin: how to compile code snippets

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-meta#195]
Help with the errors in #57

**Comment by rachelcarmena** [comment]
I've created #103 to solve the errors. It's necessary to keep that branch updated with last changes in `master` branch because I had a few issues with the last update.

**Comment by i-walker** [comment]
#103 needs to point to the branch in #57, not master. I could not review it, yet, because it hasn't been on our priorities. Once it is, I'll be happy to check out everything regarding ergonomics and the refactoring that has been made in #103 
Thank you @rachelcarmena for your help.

**Comment by rachelcarmena** [comment]
> #103 needs to point to the branch in #57, not master. I could not review it, yet, because it hasn't been on our priorities. Once it is, I'll be happy to check out everything regarding ergonomics and the refactoring that has been made in #103
> Thank you @rachelcarmena for your help.

Thanks @i-walker !! #103 points to `master` because it replaces #57. Thanks for your review!!
