### ISSUE TITLE
Arrow Meta Quotes Table

### ISSUE THREAD

**Issue by ahinchman1** [arrow-kt/arrow-meta#198]
Create a table of contents for available AST quotes and its use examples.

See:
- https://scalameta.org/docs/trees/quasiquotes.html
- https://github.com/scalameta/scalameta/blob/master/notes/quasiquotes.md

**Comment by raulraja** [comment]
Just discussed with @franciscodr how this can be integrated into the site and what needs to happen on each function so the table renders nicely. Please coordinate with him for some hints to finish the impl. thanks!

**Comment by ahinchman1** [comment]
Thank you! Will do! I was just about to reach out to @franciscodr anyway!
