### ISSUE TITLE
Create specific Twitter card for Arrow Meta

### ISSUE THREAD

**Issue by franciscodr** [arrow-kt/arrow-meta#208]
We need a specific Twitter card for Arrow Meta project instead of using the generic one for Arrow

**Comment by israelperezglez** [comment]
@franciscodr @AntonioMateoGomez I attach the twitter card

![twitter-card](https://user-images.githubusercontent.com/646886/69427174-44f8c700-0d2f-11ea-9ad7-8ae853e6f632.png)

**Comment by rachelcarmena** [comment]
Added by @franciscodr in #226
