### ISSUE TITLE
Add plugin verification tool to CI

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow-meta#272]
The [Verifier](https://github.com/JetBrains/intellij-plugin-verifier) checks the binary compatibility of ide plugins across IntelliJ Platform IDE-based products.

Adding this to CI secures that all releases wether SNAPSHOT's or Release candidates work across all Jetbrains products.
Here is a small [blog](https://blog.jetbrains.com/platform/2018/07/plugins-repository-now-integrates-with-the-plugin-verification-tool/)

**Comment by rachelcarmena** [comment]
Waiting for an official version of the GitHub Action here: https://github.com/JetBrains/intellij-plugin-verifier-github-action

**Comment by rachelcarmena** [comment]
There isn't an official version yet so [the tool](https://github.com/JetBrains/intellij-plugin-verifier) has been used directly: #613
