### ISSUE TITLE
Add button to show/hide Arrow Meta video

### ISSUE THREAD

**Issue by franciscodr** [arrow-kt/arrow-meta#280]
The main page of the Arrow Meta documentation site contains a link to the talk that Raul and Simon gave in the last Lambda World edition.

We would like to have a button on the page to show or hide the video as we did in some sections of the Arrow site. For instance:

https://arrow-kt.io/docs/patterns/dependency_injection/

**Comment by AntonioMateoGomez** [comment]
Closed through #287
