### ISSUE TITLE
Add IDEA versions to the sync bot

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-meta#310]
- [x] Extract `intellij { version = "LATEST-EAP-SNAPSHOT"  ... }`
- [x] Consider `KOTLIN_IDEA_VERSION` and `INTELLIJ_IDEA_VERSION` in the bot to sync with `KOTLIN_VERSION`
- [x] Solve problem with checks execution.
- [x] Add details in description

**Comment by rachelcarmena** [comment]
Look at #272

**Comment by i-walker** [comment]
Part of that issue is already covered with #306 
Do you think we should close this unless it encompasses more than what is in the description?
Otherwise, it is a duplicate to #272

**Comment by rachelcarmena** [comment]
> Part of that issue is already covered with #306

Thanks @i-walker , right! I'll extract that version in `gradle.properties`. Thanks!!

**Comment by rachelcarmena** [comment]
I'm working on it because there are compatibility problems between Kotlin and Kotlin plugin. It's necessary to sync all the versions.

**Comment by i-walker** [comment]
Ping me if you need help or have questions :)

**Comment by rachelcarmena** [comment]
> Ping me if you need help or have questions :)

Thanks @i-walker !!

**Comment by rachelcarmena** [comment]
First step: #354

**Comment by rachelcarmena** [comment]
Second step:  #359

**Comment by rachelcarmena** [comment]
Last step: #366 

About "Solve problem with checks execution", I was trying other GitHub Actions to create automatic pull requests to observe the behavior of checks execution. They cannot be executed to prevent an infinite loop of GitHub Actions. It doesn't matter because those checks are executed by the bot before creating the pull request. In case of failure, an issue (instead of a PR) would be created. These details will be included in the description of all pull requests created automatically by the sync bot.
