### ISSUE TITLE
Quote testing: remove quoteOutputMatches when there isn't any difference to check

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-meta#316]
When there are no differences between the source code and the quote output, the test isn't providing any value with `quoteOutputMatches`:

```
      code = { <piece of code> },
      assert = { quoteOutputMatches(<the same piece of code>) }
```

I think it could be better with these alternatives:
* Just `compiles`.
* Add expression evaluation to ensure that the generated bytecode works as expected.

**Comment by nomisRev** [comment]
Can we do this with property based testing?
That'd mean we need would need to build a `Gen` for every `KtElement`.

**Comment by rachelcarmena** [comment]
> Can we do this with property based testing?
> That'd mean we need would need to build a `Gen` for every `KtElement`.

Thanks for the feedback @nomisRev! I've updated the description.

**Comment by rachelcarmena** [comment]
And it seems property-based testing is an upcoming feature. Until then, I think we could improve these tests.

Some errors were just detected when evaluating expressions on the bytecode.

**Comment by ahinchman1** [comment]
```
Some errors were just detected when evaluating expressions on the bytecode.
```

@rachelcarmena are there specific examples with the error messages and where it's failing? I'm sorry, this is vague for me.

**Comment by rachelcarmena** [comment]
> ```
> Some errors were just detected when evaluating expressions on the bytecode.
> ```
> 
> @rachelcarmena are there specific examples with the error messages and where it's failing? I'm sorry, this is vague for me.

Or course! I'm talking about execution errors instead of compilation errors. Compilation can be OK and then the execution can raise an error. If we add the check of execution with expression evaluation, the test will be more robust :+1:

**Comment by ahinchman1** [comment]
ahhh yeah thanks so much Raquel - I still have more base ones to add for the rest of today, but perhaps I can open a PR with to experiment with some of these ideas tomorrow or Thursday so we can create a good standard for more robust testing for the quote-and-template system! 😄

**Comment by raulraja** [comment]
@nomisRev yes these are the laws I have been talking to @ahinchman1 we will build once all the elements are there. A Gen and a law set for scopes. The first law is the empty identity for the destructuring template producing no effect when an element is replaced by it. This ensures all templates as quoted are non-destructive

**Comment by rachelcarmena** [comment]
Thanks @raulraja , let's close the issue because of the upcoming features!
