### ISSUE TITLE
Consider RELEASE, DEV and EAP versions for Kotlin language

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-meta#351]
We are considering the last EAP version when there is a latest release version.

**Comment by i-walker** [comment]
We can stay at EAP for now, because of rather significant changes in the upcoming releases after 2019.3. Do we want to follow a specific strategy here?

**Comment by rachelcarmena** [comment]
> We can stay at EAP for now, because of rather significant changes in the upcoming releases after 2019.3. Do we want to follow a specific strategy here?

Thanks @i-walker! I updated the title with the reference to Kotlin language. We are considering the last EAP version (1.3.60-x) when there is a latest release version (1.3.61).

**Comment by rachelcarmena** [comment]
Done! Waiting for #366 to create another PR :tada:

**Comment by rachelcarmena** [comment]
Solved in #367.
