### ISSUE TITLE
Add Module dropdown

### ISSUE THREAD

**Issue by AntonioMateoGomez** [arrow-kt/arrow-meta#355]
Now we are going to release the new Arrow website we must to include the module dropdown in the Arrow meta sidebar, so it will work as a conector with the other modules `core`, `incubator`, `fx`, and  `optics`.

![Captura de pantalla 2019-12-18 a las 10 45 56](https://user-images.githubusercontent.com/25897490/71075011-a459c380-2183-11ea-9497-6a629482a86b.png)

**Comment by calvellido** [comment]
Closed through #357
