### ISSUE TITLE
Overload resolution ambiguity

### ISSUE THREAD

**Issue by MikeDepies** [arrow-kt/arrow-meta#368]
When I run the example found in meta-example I get this in the IDE

Overload resolution ambiguity

`e: C:\Users\depie_000\AppData\Local\kotlin\daemon\build\generated\source\kapt\main\Comphrensions.kt: (19, 1): Conflicting overloads: public fun test(): IO<Int> defined in io.arrowkt.example in file Comphrensions.kt, public fun test(): IO<Int> defined in io.arrowkt.example
`

**Comment by rachelcarmena** [comment]
Thanks @MikeDepies! Please, we'd very grateful if you could provide us more details about the problem because I cannot find `Comphrensions.kt`. Which project did you open? Did you make changes then? How did you run it? Thanks in advance!

**Comment by raulraja** [comment]
For what is worth the arrow plugins are not ready yet. They will be around March / April and will come out in the stable release of Arrow alongside the Lang release lifecycle after Kotlin 1.4

**Comment by MikeDepies** [comment]
I'm running on windows 10 for what its worth. (btw is there a guideline for issues?)

I cloned the repo, cloned the example repo. On windows running the gradle tasks with the -Dargs caused it to hang indefinitely so I ran without the arguments (I imagine source of issue). I buildMeta then publishandRunIde

I open the example repo and it breaks on build/run.

**Comment by rachelcarmena** [comment]
Thanks @MikeDepies for the info! (We have issue templates for reporting bugs now :wink: ).

The included log error indicates `Comphrensions` (it has a typo) and as far as I know `Comphrensions` doesn't exist neither in `arrow-meta` repository nor `arrow-meta-examples` repository.

`arrow-meta` and `arrow-meta-examples` are independent repositories. `arrow-meta-examples` uses artifacts that are published in repositories (some of them from `arrow-meta` repository).

You can find the guideline to run the examples with the IDE in [`How to run it from IDE`](https://github.com/arrow-kt/arrow-meta-examples/blob/master/README.md) sections.

**Comment by MikeDepies** [comment]
Oh excellent. Looks like I was turned around. I was able to run the hello world example. Thank you. Is there an easy path for me to integrate the counterpart helloworld intelij plugin as well?
