### ISSUE TITLE
[BUG] New declaration is not discoverable by IDE

### ISSUE THREAD

**Issue by kptlronyttcna** [arrow-kt/arrow-meta#389]
**Describe the bug**
New declarations are not discoverable by IDE.

**To Reproduce**
Change HelloWorldPlugin in [examples](https://github.com/arrow-kt/arrow-meta-examples) to declare a new function. For example `helloWorld2` instead of `helloWorld`. Then use `helloWorld2` in main. The program compiles successfully and works, but the IDE can't find `helloWorld2` and shows it in red.

**Expected behavior**
I'm not sure if I can expect the IDE to recognize that new function. If this is not a bug, is there a way to make the IDE see the transformed AST?

**Comment by rachelcarmena** [comment]
Hi @kptlronyttcna , thanks for your feedback! Please, could you confirm us that:

```
fun helloWorld(): Unit = TODO()
```

was also updated when doing that change? 

Thanks in advance!

**Comment by kptlronyttcna** [comment]
I don't know how to check that. But I know that helloWorld2 was indeed defined as the program compiled and ran successfully. This is the code I used:

```
val Meta.helloWorld: Plugin
  get() =
    "Hello World" {
      meta(
        namedFunction({ name == "helloWorld" }) { c ->
          Transform.replace(
            replacing = c,
            newDeclaration =
            """|fun helloWorld2(): Unit =
               |  println("Hello ΛRROW Meta!")
               |""".function.syntheticScope
          )
        }
      )
    }
```

**Comment by rachelcarmena** [comment]
Great, thanks @kptlronyttcna ! And did you change `hello-world/use-plugin/src/main/kotlin/io/arrowkt/example/HelloWorld.kt`?

**Comment by kptlronyttcna** [comment]
Yes, forgot to mention that.

```
package io.arrowkt.example

//metadebug

fun helloWorld(): Unit = TODO()

fun main() {
  helloWorld2() <---- Changed this line. It compiles and works but Intellij shows it in red and does not autocomplete
}
```

**Comment by rachelcarmena** [comment]
Thanks @kptlronyttcna ! Please, try to update the `helloWorld` function as well and reopen in case it doesn't work. Thanks!!

**Comment by kptlronyttcna** [comment]
So at the end, are you saying that I cannot expect the IDE to recognize new declarations defined with arrow meta? Imagine instead of using Transform.replace, I use some other transform to add helloWorld2 while leaving helloWorld untouched. Can the IDE know about helloWorld2 even though it's not anywhere in the code but will be declared by arrow meta during compilation? This is possible with annotation based code-gen tools, I was wondering if it would be possible with arrow meta as well.

**Comment by MikeDepies** [comment]
You have to create a counterpart IDE plugin for your compiler plugin. Meta facilitates this as well. So its possible, but this example does not showcase it.

**Comment by kptlronyttcna** [comment]
A sample showcasing that feature would be awesome.
