### ISSUE TITLE
[BUG] Stabilize IDE in sv-test-proofs branch

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow-meta#457]
**Describe the bug**
Once again the IDE piece seems broken regarding changes coming from master.

**To Reproduce**
run the IDEA in the sv-test-proofs

**Expected behavior**
IDE is stable and proofs icons etc are recognized.

**Additional context**
Please commit fixes to IDE part directly to sv-test-proofs branch.

**Comment by i-walker** [comment]
#461 may resolve the Bug that was raised. Please, send in any errors that we're not considered in that PR.

**Comment by raulraja** [comment]
Not blocking me at the moment

**Comment by i-walker** [comment]
Can we close it?
