### ISSUE TITLE
Add ResolveScopeEnlarger extension

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow-meta#465]
- [ ] add a directory in `arrow.meta.ide.dsl` called `resolve`
- [ ] create an interface `ResolveScopeSyntax`, which creates a meta dsl for `com.intellij.psi.ResolveScopeEnlarger`
- [ ] create an minimal example and Docs on what an `ResolveScopeEnlarger` does. Please add those in a Kdoc.

Note:
This [link]( https://meta.arrow-kt.io/docs/apidocs/idea-plugin/arrow.meta.ide.dsl.extensions/-extension-provider-syntax/extension-provider.html) is helpful to understand how the meta dsl in the ide is constructed.
Check out these instances `org.jetbrains.android.AndroidResolveScopeEnlarger`, `org.jetbrains.kotlin.idea.CommonModuleResolveScopeEnlarger` in the [kotlin compiler](https://github.com/JetBrains/kotlin/tree/1.3.70)

**Comment by matiaslev** [comment]
please let me look at it

**Comment by i-walker** [comment]
Resolved with #479 :) Thanks @matiaslev
