### ISSUE TITLE
Add ResolveScopeProvider extension

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow-meta#480]
- [x] add or use the directory in arrow.meta.ide.dsl called resolve
- [x] create an interface `ResolveProviderSyntax`, which creates a meta dsl for com.intellij.psi.ResolveScopeProvider

Note:
This [link](https://meta.arrow-kt.io/docs/apidocs/idea-plugin/arrow.meta.ide.dsl.extensions/-extension-provider-syntax/extension-provider.html) is helpful to understand how the meta dsl in the ide is constructed.
Check out these instances [`KotlinScriptResolveScopeProvider`](https://github.com/JetBrains/kotlin/blob/fb01f7be5ed29a45df67497c7bcb44d4eb1f16a8/idea/idea-core/src/org/jetbrains/kotlin/idea/core/script/dependencies/KotlinScriptResolveScopeProvider.kt#L32) or [`ScriptDependenciesResolveScopeProvider`](https://github.com/JetBrains/kotlin/blob/eca7bbdb8ce333658eafa7c4669cbaa55c178d0d/idea/idea-core/src/org/jetbrains/kotlin/idea/core/script/dependencies/ScriptDependenciesResolveScopeProvider.kt#L26).

**Comment by arioston** [comment]
I will work on this issue

**Comment by i-walker** [comment]
Resolved with #481 
Thanks @arioston :)
