### ISSUE TITLE
Stabilize IDE in `sv-test-proofs` branch

### ISSUE THREAD

**Issue by raulraja** [arrow-kt/arrow-meta#499]
Currently running the IDE exhibits several exceptions and we also have issues with dependency management. (@rachelcarmena )

Once that is stable this is a list of visual features we want to add to the type proofs plugin in the IDE (@danimontoya, @aballano, @i-walker)

# Type Proofs
- A Visual chart that displays proofs connection between proofed types using nomnoml or diagram plugin 
- Dialog over proof icons that display the effect the proof has with examples
- Include implicit call sites in the usages of proofs when using Find Usages
## Type Classes
- Show an extension is connecting the behavior with the datatype with a type class icon.
- A visual clue for a call site where a type class gets injected
- An intention to make the implicit injection explicit
- An intention to make the explicit injection implicit
## Coercion functions
- A visual representation when a type coercion occurs by proof
- An intention to make the implicit coercion explicit
- An intention to make the explicit coercion implicit
## Union Types
- Simplify display of `Union2<A, B>` to `A | B` when displayed in the editor and back to edit mode when focused
## Tuple Types
- Simplify display of `Tuple2<A, B>` to `(A, B)` when displayed in the editor and back to edit mode when focused
## Refined Types
- A visual representation for refined classes + dialog.
- A visual representation for safe/unsafe usage of call sites that abide to the refinement.
- A visual representation for each one of the refined predicates that showcases they are compile time verified.

**Comment by rachelcarmena** [comment]
> Currently running the IDE exhibits several exceptions and we also have issues with dependency management. (@rachelcarmena )

I checked to add just `compiler-plugin` dependency with different configurations to get transitive dependencies automatically and to avoid the hard-coded dependencies list in Gradle Plugin, however they aren't added. 

I'll get the transitive dependencies list programmatically. Take into account : `compileOnly` dependencies are not transitive dependencies just `compile` or `api` so `org.jetbrains.kotlin:kotlin-compiler-embeddable:$KOTLIN_VERSION"` (`compileOnly`) is not included in the transitive dependencies list.

**Comment by danimontoya** [comment]
Shall we close this issue? `sv-test-proofs` got merged and we've created #543

**Comment by rachelcarmena** [comment]
> I checked to add just `compiler-plugin` dependency with different configurations to get transitive dependencies automatically and to avoid the hard-coded dependencies list in Gradle Plugin, however they aren't added.
> 
> I'll get the transitive dependencies list programmatically. Take into account : `compileOnly` dependencies are not transitive dependencies just `compile` or `api` so `org.jetbrains.kotlin:kotlin-compiler-embeddable:$KOTLIN_VERSION"` (`compileOnly`) is not included in the transitive dependencies list.

Solved via #580 and #585

**Comment by rachelcarmena** [comment]
Sorry, it was closed automatically when merging #585.
