### ISSUE TITLE
Adapt idea-plugin for Intellij IDEA 2020.1.1

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-meta#526]
## Context

The bot raised this issue today  https://github.com/arrow-kt/arrow-meta/issues/524 when trying the new version of Intellij IDEA:

* Intellij IDEA=2020.1.1

and:

* Kotlin=1.3.71
* Kotlin IDEA=1.3.71-release-IJ2020.1-1

However that Intellij IDEA version is compatible with Kotlin 1.3.61 (the current version on master branch) so **the issue can be fixed without waiting for the upgrade to Kotlin 1.3.71**.

![Screenshot from 2020-04-08 16-43-35](https://user-images.githubusercontent.com/22792183/78797685-50841c00-79b8-11ea-920f-a4f2d28b9842.png)

## Some changes

I've done these changes to get a green build for the bot and to avoid having an issue every day:

* Avoid overriding removed functions.
* Replace `PlatformComponentManagerImpl` by `ComponentManagerImpl`
* Replace `FontEditorPreview.getIDEDemoText()` by the content of that function (it's private now in a deprecation cycle)
* Changes related to a signature change of the listener parameter for `com.intellij.openapi.wm.ToolWindowManager.notifyByBalloon`
* Other small changes
* Ignore `QuoteCacheTest` tests :point_left: :point_left: :point_left: Failures:
```
com.intellij.openapi.progress.ProcessCanceledException: com.intellij.serviceContainer.AlreadyDisposedException: Cannot create ServiceAdapter(descriptor=ServiceDescriptor(interface=org.jetbrains.kotlin.idea.caches.resolve.IdePackageOracleFactory, implementation=org.jetbrains.kotlin.idea.caches.resolve.IdePackageOracleFactory), pluginDescriptor=PluginDescriptor(name=Kotlin, id=org.jetbrains.kotlin, path=/home/rachel/workspace/arrow-meta/idea-plugin/build/idea-sandbox/plugins-test/Kotlin)) because container is already disposed (container=Project (name=light_temp, containerState=ACTIVE, componentStore=/tmp/unitTest_incrementalCacheUpdate5/light_temp.ipr)  (disposed temporarily))
java.lang.RuntimeException: com.intellij.openapi.progress.ProcessCanceledException: com.intellij.serviceContainer.AlreadyDisposedException: Cannot create ServiceAdapter(descriptor=ServiceDescriptor(interface=org.jetbrains.kotlin.idea.caches.resolve.IdePackageOracleFactory, implementation=org.jetbrains.kotlin.idea.caches.resolve.IdePackageOracleFactory), pluginDescriptor=PluginDescriptor(name=Kotlin, id=org.jetbrains.kotlin, path=/home/rachel/workspace/arrow-meta/idea-plugin/build/idea-sandbox/plugins-test/Kotlin)) because container is already disposed (container=Project (name=light_temp, containerState=ACTIVE, componentStore=/tmp/unitTest_incrementalCacheUpdate5/light_temp.ipr)  (disposed temporarily))

ERROR: Invalid parent: temp:///src/testArrow of file temp:///src/testArrow/second.kt, file.valid=false
java.lang.Throwable: Invalid parent: temp:///src/testArrow of file temp:///src/testArrow/second.kt, file.valid=false
```

Those changes can be seen in https://github.com/arrow-kt/arrow-meta/pull/525 which prepares a file for the bot to apply it when trying the new versions: https://github.com/arrow-kt/arrow-meta/pull/525

Just run:

```
git apply .github/workflows/sandbox/1.3.70-eap.diff
```

and discard changes on `compiler-plugin` to get those changes on your local workspace.

## Pending task 

Fixing `QuoteCacheTest` because those tests were ignored now.

I think we could fix them to upgrade Intellij IDEA version **without waiting for** upgrading to 1.3.71.

cc: @jansorg @i-walker

**Comment by i-walker** [comment]
I've addressed some errors in the patch in this PR #545
