### ISSUE TITLE
Github patch

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow-meta#557]
Patch commits shall run tests and build the underlying plugins, before being approved by CI. Currently, when enabling `check for next`, the checks reflect on the git diff conflicts and the compiler, but the [ide build](https://github.com/arrow-kt/arrow-meta/blob/aa155a3a08905feb795cdc274372ed0cf7f48184/.github/workflows/build_artifacts.yml#L52) is missing.

Just leaving this as a reminder :)

**Comment by rachelcarmena** [comment]
Thanks @i-walker :raised_hands: It's not possible to run `ide` build for next Kotlin versions (DEV and EAP) because Kotlin IDE plugin just exist for Kotlin release versions.
