### ISSUE TITLE
[Issue?] How to handle this coercion scenario

### ISSUE THREAD

**Issue by danimontoya** [arrow-kt/arrow-meta#588]
( relates to #567 ) Having defined these coercion proofs: 
```
@Coercion
fun String.toInteger(): Int? = this.toInt()

@Coercion
fun Int.toText(): String = this
```
I noticed of one possible scenario where the user can do something like:
```
val coercion: String? = "23".toInteger()?.toText()
```
Which is still valid.. but if the user applies the fix we give.. the result will look like:
```
val coercion: String? = "23"?.toText() This is invalid after applying the fix
```
Which is an invalid property.. so how should we handle it?

**Comment by raulraja** [comment]
whenever the target expression is a constant `"23"` vs a free variable `s` you need to get rid of the last `?`. If the compiler still bails we need to look into proofs internals to see if the coercion is possible. In the meantime, if it does not work accounting for constants vs free variables you can make this not suggest to be converted implicitly

**Comment by danimontoya** [comment]
After meeting @raulraja, decision made is that we are not highlighting this specific case for now.. until we have the inductive coercion.
