### ISSUE TITLE
Union type line marker icon

### ISSUE THREAD

**Issue by danimontoya** [arrow-kt/arrow-meta#604]
Addresses part of #602 
We need an **icon** to represent the union types. Whenever the union type is used, this icon will be shown
It should look something like this: `U`
It will be to be shown on the side.. like:
![arrow-meta-coproduct](https://user-images.githubusercontent.com/9677245/81427794-910fba80-915b-11ea-8ddc-75749fe59815.png)
cc @raulraja

**Comment by israelperezglez** [comment]
@danimontoya I attach the icons ;)
[arrow-meta-union-types.zip](https://github.com/arrow-kt/arrow-meta/files/4754312/arrow-meta-union-types.zip)

**Comment by danimontoya** [comment]
@israelperezglez they look good! thank you isra! 🎉
