### ISSUE TITLE
Intellij IDEA shows errors with the sources used during testing

### ISSUE THREAD

**Issue by rachelcarmena** [arrow-kt/arrow-meta#728]
Reported by Slava Kornienko:

![image(1)](https://user-images.githubusercontent.com/22792183/90014401-47c58e80-dca7-11ea-82b8-709724869ad5.png)

It's confusing because it finishes successfully

**Comment by rachelcarmena** [comment]
I'm doing tests and it just happens with "composed" Gradle tasks.

For instance, it happens with `build` because it runs `assemble` and `check`. However, it works properly with only `check`.

I didn't find a way to disable this feature. I'm going to ask to Gradle team. Meanwhile I'm going to change `buildMeta` to avoid this misunderstanding.

**Comment by rachelcarmena** [comment]
It cannot be avoided with `buildMeta` because it seems every custom task is composed by other tasks so it shows the errors.

The only way I found to avoid it so far:
- Don't use `buildMeta`
- Use `check` or `testClasses` for a module (not from the root project because it will be run several tasks)

**Comment by Starmel** [comment]
With `./gradlew buildMeta` got the same way test run error: https://gist.github.com/Starmel/b82bce2c93bdf474e7be40762abf3aee

<details>
<summary>Details</summary>

```
arrow.meta.plugin.testing.ExampleTest > allows to test a Meta plugin FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting:
     <INTERNAL_ERROR>
    to be equal to:
     <OK>
    but was not.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at arrow.meta.plugin.testing.CompilationAssertionsKt.assertCompiles(CompilationAssertions.kt:140)
        at arrow.meta.plugin.testing.CompilationAssertionsKt.assertEvalsTo(CompilationAssertions.kt:126)
        at arrow.meta.plugin.testing.CompilationAssertionsKt.access$assertEvalsTo(CompilationAssertions.kt:1)
        at arrow.meta.plugin.testing.CompilationAssertionsKt$interpreter$1$4.invoke(CompilationAssertions.kt:100)
        at arrow.meta.plugin.testing.CompilationAssertionsKt$interpreter$1.invoke(CompilationAssertions.kt:111)
        at arrow.meta.plugin.testing.CompilationAssertionsKt$interpreter$1.invoke(CompilationAssertions.kt)
        at arrow.meta.plugin.testing.CompilerTest.run$meta_test(CompilerTestDSL.kt:55)
        at arrow.meta.plugin.testing.CompilationAssertionsKt.assertThis(CompilationAssertions.kt:61)
        at arrow.meta.plugin.testing.ExampleTest.allows to test a Meta plugin(ExampleTest.kt:177)
```

</details>

**Comment by i-walker** [comment]
For me, that resolves when applying `cleanMeta` first @Starmel

**Comment by Starmel** [comment]
> For me, that resolves when applying `cleanMeta` first @Starmel

Same error log with `./gradlew cleanMeta buildMeta `

<details>
<summary>JVM info</summary>
 java.vm.vendor : Oracle Corporation, 
    sun.arch.data.model : 64, 
    user.variant : , 
    java.vendor.url : https://java.oracle.com/, 
    user.timezone : Europe/Moscow, 
    java.vm.specification.version : 13, 
    os.name : Mac OS X, 
    user.country : RU, 
    sun.java.launcher : SUN_STANDARD, 
    sun.boot.library.path : /Library/Java/JavaVirtualMachines/openjdk-13.0.2.jdk/Contents/Home/lib, 
    sun.java.command : worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 1', 
    http.nonProxyHosts : local|*.local|169.254/16|*.169.254/16, 
    jdk.debug : release, 
    sun.cpu.endian : little, 
    user.home : /Users/admin, 
    user.language : ru, 
    java.specification.vendor : Oracle Corporation, 
    org.gradle.native : false, 
    java.version.date : 2020-01-14, 
    java.home : /Library/Java/JavaVirtualMachines/openjdk-13.0.2.jdk/Contents/Home, 
    file.separator : /, 
    java.vm.compressedOopsMode : Zero based, 
    line.separator : 
    , 
    java.vm.specification.vendor : Oracle Corporation, 
    java.specification.name : Java Platform API Specification, 
    idea.use.native.fs.for.win : false, 
    sun.management.compiler : HotSpot 64-Bit Tiered Compilers, 
    ftp.nonProxyHosts : local|*.local|169.254/16|*.169.254/16, 
    java.runtime.version : 13.0.2+8, 
    user.name : admin, 
    path.separator : :, 
    os.version : 10.15.6, 
    java.runtime.name : OpenJDK Runtime Environment, 
    file.encoding : UTF-8, 
    java.vm.name : OpenJDK 64-Bit Server VM, 
    java.vendor.url.bug : https://bugreport.java.com/bugreport/, 
    java.io.tmpdir : /var/folders/_w/94xwc7ys48xd7n4dk69tvkz40000gn/T/, 
    java.version : 13.0.2, 
    user.dir : /Users/admin/Dev/os/arrow-meta/meta-test, 
    os.arch : x86_64, 
    java.vm.specification.name : Java Virtual Machine Specification, 
    CURRENT_VERSION : 1.3.61-SNAPSHOT, 
    java.library.path : /Users/admin/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:., 
    java.vm.info : mixed mode, sharing, 
    java.vendor : Oracle Corporation, 
    java.vm.version : 13.0.2+8, 
    sun.io.unicode.encoding : UnicodeBig, 
    socksNonProxyHosts : local|*.local|169.254/16|*.169.254/16, 
    java.class.version : 57.0]
</details>

**Comment by rachelcarmena** [comment]
Hi @Starmel , thank you so much for your feedback!! I think that error would be a different issue however I see JDK 13 is being used. Please, try it with JDK 8. Sorry, this requirement should appear in the README file together the Gradle tasks... Would you like to add it? Thanks again!

**Comment by Starmel** [comment]
Yeah, with it all works from terminal.
<details>
<summary>Information about wornking JDK version</summary>
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_265-b01)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.265-b01, mixed mode)
</details>

And i had figured out reason why not working from Idea. Probably, Idea parsing System.Out of Gradle result and consume any lines with format 
```
warning: /../demo/kinds/kinds.kt: (22, 28): Unchecked cast: Any? to List<A>
```
```
error: <SOURCE_FILE_PATH:LINE:MESSAGE>
```
as project compiler logs.


<details>
<summary>Solution</summary>
We can fix it with suspressing output of compiler-test-library using stub output stream


Example:

```kotlin
KotlinCompilation().apply {

  .. exist code

  messageOutputStream = object : OutputStream() {
    override fun write(b: Int) {
		// Stubbed!
    }
  }
}.compile()
```
</details>


What do you are thing about adding output stream stub? Do compiler-test-library output logs is using in debugging? If yes, probably solution - transform logs with format, that not triggering Idea and understandable for debugging. Or just stub it.

**Comment by Starmel** [comment]
It's not a bug, it's a feature. Heh

![image](https://user-images.githubusercontent.com/8287942/90309102-e04d5000-deed-11ea-85f3-949bcff8ba27.png)

**Comment by rachelcarmena** [comment]
Thanks @Starmel !! I think the errors shown when running `buildMeta` come from the IDE because they aren't shown when running that Gradle task from command line. It seems the IDE is checking the sources used during testing (`Source.kt` files in `/tmp` directory). 

It seems those errors don't come from Kotlin IDE Plugin or IDE inspections (they don't disappear without them). And I don't think they come from the log messages but checks done by the IDE on all the sources.

It's curious because errors are shown when running "composed" Gradle tasks. If you run `check` Gradle task for `meta-test` module, for instance, errors don't raise. However, when running a custom Gradle task which runs `check` for that module shows the error.

I tried to update `Ignore Files and Folders` from `Settings > Editor > File Types`... no success!

I hope there is a solution beyond writing a note about those errors :pray:

**Comment by rachelcarmena** [comment]
Thanks @Starmel !! Sorry, I misunderstood the IDE behavior because it opened the failed files. Error messages appear with the same complaints from the IDE. For instance:

```
e: /tmp/Kotlin-Compilation7925263625332920329/sources/Source.kt: (1, 1): Expecting a top level declaration
```

I think your alternative removes the output from compilation so let's look for another alternative to keep it without `e:`

**Comment by Starmel** [comment]
I will make PR with changes, that transforms logs with preventing false-error output.

**Comment by rachelcarmena** [comment]
> I will make PR with changes, that transforms logs with preventing false-error output.

Sorry @Starmel  I created #733. I would be very grateful if you could review it. Thank you so much!! :raised_hands:
