### ISSUE TITLE
Kotlin type classes and multiple receivers 

### ISSUE THREAD

**Issue by LifeIsStrange** [arrow-kt/arrow-meta#766]
I don't know if there's a relationship but the Kotlin team is currently prototyping multiple receivers and I have no idea if that could help with type classes but hey here's the issue, feel free to close it if it's not relevant! 
https://youtrack.jetbrains.com/issue/KT-10468

**Comment by raulraja** [comment]
We are aware and very much looking forward to multiple receivers but the proofs and type class system in meta is now further along of what you can do with multiple receivers for expression injection, semi automatic derivation and others.
