### ISSUE TITLE
@with Variance

### ISSUE THREAD

**Issue by i-walker** [arrow-kt/arrow-meta#773]
Which variance is admired. 

Given this [example](https://github.com/arrow-kt/arrow-meta/blob/48982f09f691afc9c915213e308d6591046721ed/compiler-plugin/src/test/kotlin/arrow/meta/plugins/typeclasses/TypeClassesTest.kt#L42) from the `@Given` tests

```kotlin
fun <A: @Given Semigroup<A>> A.mappend(b: A): A =
          this@mappend.combine(b)
```

the compiler injects the Monoid instance.

Shall an `@with<out A>` have the same behavior or else?

```kotlin
 fun <A> @with<Semigroup<A>> A.mappend(b: A): A =
          combine(b)
```

**Comment by raulraja** [comment]
Annotations will not be used in type args but in the receiver. Variance should be taken care automatically already as part of the resolution. I don't think there is anything to implement there beyond ensuring the annotation generated from the decorator has the same variance
