### ISSUE TITLE
[BUG] Local inspection doesn't work in IDE

### ISSUE THREAD

**Issue by DisPony** [arrow-kt/arrow-meta#785]
I've tested purity plugin as example. At IDE startup component register produces following log. In opened project with some "impure" functions there are no inspection errors 

```
Registering ide plugin: Plugin(name=PurityPlugin, meta=arrow.meta.ide.phases.IdeContext.() -> kotlin.collections.List<arrow.meta.phases.ExtensionPhase>) extensions: [AddExtension(EP_NAME=com.intellij.localInspection, impl=InspectionEP{shortName='null', key='null', bundle='null', displayName='null', groupKey='null', groupBundle='null', groupDisplayName='null', groupPath='null', enabledByDefault=false, applyToDialects=true, cleanupTool=false, level='null', hasStaticDescription=false, presentation='null', isInternal=false, getImplementationClassName()='null', language=null}, loadingOrder=first)]
```

**Steps to reproduce the behavior:**
1. Checkout master branch (commit f08ebe66d43686bd19c1b2c12fe11896ef1ce6e0 at the moment i write this issue)
2. In `IdeMetaPlugin.kt` add
```kotlin
open class IdeMetaPlugin : MetaPlugin(), MetaIde {
  @ExperimentalContracts
  override fun intercept(ctx: IdeContext): List<IdePlugin> =
    listOf(
      initialIdeSetUp,
      quotes,
      typeProofsIde,
      purity
    )
}
```
2.1 In `IdeInternalRegistry.kt`, replace 
`println("Registering ide plugin: $it extensions: ${it.meta}")`
with 
`println("Registering ide plugin: $it extensions: ${it.meta(ctx)}")`
So we can see extension representations
3. Run gradle task "idea-plugin:runIde"
4. Clone https://github.com/DisPony/purity_plugin_playground 
or create new project and paste this code in some file
```kotlin
package test

fun impure(): Unit = println("Hello, world")
```

**Expected behavior**
At this point gradle task produces log i've mention before. Function `impure` should be highlighted as error, but it isn't

**Environment**
 - Kotlin version 1.4.10: 
 - Kotlin Intellij IDEA plugin version 1.4.10-release-IJ2020.2-1: 
- Intellij IDEA version: 
IntelliJ IDEA 2020.2.3 (Community Edition)
Build #IC-202.7660.26, built on October 6, 2020

**Additional context**
I wrote simple IDE test for purityInspection itself and it works as expected
https://gist.github.com/cd1b47c756ef090310b227a26ef99333

**Comment by i-walker** [comment]
Hello @DisPony :D 
May you please check in your IDE Preferences under `Editor` -> `Inspection` and look for the Path you have set for your plugin, that it is enabled. Here is one example: 
https://github.com/arrow-kt/arrow-meta/blob/d97c914cdcd3075122f4398cee3dbb5cafa0142b/idea-plugin/src/main/kotlin/arrow/meta/ide/plugins/purity/PurityPlugin.kt#L25
where the Path is `Kotlin, Arrow, PurityPlugin`
Below is an Inspection, which is not enabled.
<img width="351" alt="Screenshot 2020-12-13 at 22 40 09" src="https://user-images.githubusercontent.com/46971368/102024751-3810a080-3d94-11eb-80d9-b5b6d8899005.png">

If you have any follow up questions, feel free to drop them here. 
We're working on ensuring that in each spun up Ide instance that the statically set [`Enabled/Disabled`](https://github.com/arrow-kt/arrow-meta/blob/d97c914cdcd3075122f4398cee3dbb5cafa0142b/idea-plugin/src/main/kotlin/arrow/meta/ide/dsl/editor/inspection/InspectionSyntax.kt#L113) works consistently in Debug-mode,  but that's still in the works.

**Comment by DisPony** [comment]
@i-walker Hello, and thank you! Indeed, now when i enabled inspection in preferences everything works as expected. 
Also thank you and the team for everything about Arrow Meta :D All the possibilities and implemented features are very exciting.

**Comment by i-walker** [comment]
You're welcome @DisPony 😄
