### ISSUE TITLE
[BUG] publication.gradle is missing

### ISSUE THREAD

**Issue by koperagen** [arrow-kt/arrow-meta#788]
Top-level build.gradle script [uses](https://github.com/arrow-kt/arrow-meta/blob/master/build.gradle#L59) publication.gradle, but URL returns 404 error

**To Reproduce**
1. Check out master
2. Import Gradle project 
3. See an error in logs

**Expected behavior**
Able to build project & publish to maven local

**Screenshots**
![image](https://user-images.githubusercontent.com/12936457/110127164-5657cc80-7dd6-11eb-9dae-e48f22716c35.png)

![image](https://user-images.githubusercontent.com/12936457/110127471-be0e1780-7dd6-11eb-90ea-7fd3061ae635.png)

**Comment by koperagen** [comment]
This script was deleted in the arrow repository. As a workaround, I use a version from history https://raw.githubusercontent.com/arrow-kt/arrow/8016a5cf41ebb1865af58abecd3f3785afe03505/gradle/publication.gradle

**Comment by rachelcarmena** [comment]
Thank you so much @koperagen !!

The file exists in another location because of the reunification of repositories. The new location was added in the review of your pull request: https://github.com/arrow-kt/arrow-meta/pull/789

Thank you!! :raised_hands:

**Comment by rachelcarmena** [comment]
Solved via #790.
