### ISSUE TITLE
[BUG] compiler-plugin java class files are on version 55

### ISSUE THREAD

**Issue by stabbylambda** [arrow-kt/arrow-meta#794]
**Describe the bug**
It looks like the latest snapshot published was compiled with JDK 11 and all the Kotlin source files got compiled for compatibility with Java 1.8, but the *Java* source files wound up being Java 11 format. 

```
❯ javap -classpath `pwd`/compiler-plugin-1.4.10-SNAPSHOT.jar -verbose arrow/meta/diagnostic/MetaDefaultErrorMessages  | grep major
  major version: 55
```

I know the actions explicitly set JAVA_HOME to Java 8, but perhaps the latest snapshot was published without that. The other potential fix would just be to update targetCompatibility for java in compiler-plugin/build.gradle

```
java {
    targetCompatibility = JavaVersion.VERSION_1_8
}
```

**Comment by rachelcarmena** [comment]
Thanks for the warn @stabbylambda !

Let's fix the actions firstly :raised_hands:

**Comment by rachelcarmena** [comment]
Please, re-open if it still happens to you. Thank you so much again!! :raised_hands:
