### ISSUE TITLE
Designs for upcoming presentation Kotlin talks

### ISSUE THREAD

**Issue by JetroCabau** [arrow-kt/arrow-meta#84]
Hi team!
I created this issue to keep in mind all the material we have to develop for Kotlin's presentations.
Feel free to edit this issue to add more information, dates, etc..
@ahinchman1 @rachelcarmena 

### Kotlin Days: London
Deadline for presentation design: Friday 22 November `(?)` TBD
Meeting date: `Thursday 8 November at ??:??` TBD
[Slides](https://docs.google.com/presentation/d/1_ETFC_CxOsQQagXFAvs90FN_lqKq6UZRa9lP-CQ8hm0/edit?usp=sharing)

### KotlinConf: Copenhagen
Deadline for presentation design: 
Meeting date: 

### JFuture Belarus
Deadline for presentation design: 
Meeting date:

Thanks!

**Comment by ahinchman1** [comment]
Thank you Jetro!

I'll be posting ideas as they come. 

**Animation of how Arrow-meta hooks into the Kotlin compiler**

A brief overview of the Kotlin compiler and how Arrow-meta hooks itself in various stages of the compiler - maybe something fun, like kicking out the replacing functions written in idea/compiler plugin (Alien? a comic?)

** Story animation about Arrow-meta and KEEPS**
@rachelcarmena has already started a nice story line for Arrow-meta covering the KEEPS portion, so we're already a leg up on this talk so we can focus on the more technical aspects of our talk. For the existing story line found in  Rachel's story, it would be cool to have some kind of set of animations for a "quest" done in the medieval art we have on those tshirts from Lambda World or the Book of Arrow art

**Comment by ahinchman1** [comment]
An idea from @raulraja from slack:

```
a thought for the talk we should have had on slides in ours is to let everyone know that any feature from meta, arrow or the plugins adopted by the language will be removed from meta including meta itself
```

Please feel free to add more context to this, but I just thought to post it up here as I saved this comment to our short list thus far.

**Comment by raulraja** [comment]
This belongs in Marlow. Jetro asked me to remove this. Auto destroying in... 3, 2, 1
