### ISSUE TITLE
[BUG] @annotations as ScopedList type have wrong separator

### ISSUE THREAD

**Issue by paranoidmonoid** [arrow-kt/arrow-meta#893]
**Describe the bug**
`@annotations` in `ClassOrObjectScope` class are of `ScopedList` type. The default separator for `ScopedList` is a comma and no custom separator is passed. This results in the following: if there's more than one annotation, they become concantenated with comma when casted to string.

**To Reproduce**
See branch reproducer: https://github.com/paranoidmonoid/kotlin-serial-name/tree/reproducer-commas
Run Main
In console output you will see the following (which doesn't show the full issue)
`Exception in thread "main" kotlinx.serialization.SerializationException: Serializer for class 'Cat' is not found.
Mark the class as @Serializable or provide the serializer explicitly.`

To get more precise logs, in "serial name plugin" add something like `error(newDeclaration)` below `newDeclaration`
Note, that annotations in logs are separated with commas:
```
java.lang.IllegalStateException: @Serializable, @SerializeWithStrategy(SerializationStrategy.KebabCase) data class Cat(@SerialName("nickname") val name: String, @kotlinx.serialization.SerialName("age") val age: Int, @kotlinx.serialization.SerialName("owner-name") val ownerName: String, @kotlinx.serialization.SerialName("breed") val breed: String) {}
```

**Expected behavior**
A custom separator (whitespace) will be passed like for `declarations` in `ClassOrObjectScope`

**Screenshots**

**Environment (please complete the following information):**
- KOTLIN_VERSION=1.5.31
- JVM_TARGET_VERSION=1.8
- ARROW_VERSION=1.0.0
- ARROW_META_VERSION=1.5.0-RC-SNAPSHOT
- Kotlin: 212-1.5.31-release-546-IJ4638.7

**Comment by serras** [comment]
Closed by #915
