### ISSUE TITLE
Question: Where do I get BindingContext?

### ISSUE THREAD

**Issue by vnermolaev** [arrow-kt/arrow-meta#960]
I am using Arrow Meta in my project to analyse the properties of the class. As such:
```kotlin
val Meta.PropertyAnnotator: CliPlugin
    get() = "My processor" {
        meta(
            property(this, match = { true}) { (ktProperty, descritor) ->               
                Transform.replace(
                    replacing = ktProperty,
                    newDeclaration = identity()
                )
            }
        )
    }
```

It would be really handy to get a grip on Kotlin resolved types, i.e., `ktProperty.kotlinType(bindingContext)`, but I have no idea and neither can I gain any documentation on where I can find `bindingContext: BindingContext`.

I will appreciate any tips.

**Comment by serras** [comment]
Within the block after the string with the name you have access to a `CompilerContext` as the receiver:

```kotlin
operator fun String.invoke(phases: CompilerContext.() -> List<ExtensionPhase>): CliPlugin
```

This means that everything in the `CompilerContext` is readily available. In your case, you have a `bindingTrace`, which in turn contains the `bindingContext` you are looking for.

Hope this helps :)
